version: '{build}'

init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }

branches:
  only:
  - master

build:
  verbosity: minimal

cache:
  - packages -> **\packages.config
  
platform: Any CPU
configuration: DEVELOPMENT

pull_requests:
  do_not_increment_build_number: true

before_build:
  - nuget restore Auth.FWT.sln