version: '{build}'

init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }

branches:
  only:
  - master

build:
  verbosity: minimal
  publish_wap: true

cache:
  - packages -> **\packages.config
  
platform: Any CPU
configuration: Release

pull_requests:
  do_not_increment_build_number: true

before_build:
  - nuget restore Auth.FWT.sln

deploy:
    provider: WebDeploy
    server:https://devauthfwt.scm.azurewebsites.net:443/msdeploy.axd?site=devauthfwt
    website:devauthfwt
    username:
        secure: bz6UoujGhzcfrJ3HrvmjGg==
    password:
        secure: CNFWL5eYjDQnrNYmy/K09uLnxb4+/01+9Az3VUew32QGw0MOcBdkHGIczXKxb7t4C28v6/McQncGtTfkNXjUTA==
    ntlm: false
    remove_files: false
    app_offline: true