version: '3.4'

services:
  auth:
    image: fwtl/auth:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CONFIGURATION=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    volumes:
      - $APPDATA/Microsoft/UserSecrets/a9bc6788-be8c-4fc4-acd7-b9fde6b20819:/root/.microsoft/usersecrets/a9bc6788-be8c-4fc4-acd7-b9fde6b20819
      # - $HOME/.microsoft/usersecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID
